REDEMEの更新　#1
human-osaka-game-2020/nakano_repository pull request #3
Opened 2020-10-22 02:01 UTC by yuki-nakano

* DxLibの導入手順の記載  
* 環境変数の記載

2020-11-09 06:46 UTC, taishi-matsumura commented on README.md
> +システム環境変数に新規で変数名に**DxLib**、変数値に先ほどコピーしたファイルパスの追加をしてください。次にシステム環境変数内からPathを探し編集から新規で<b>%DxLib%</b>の追加をお願いします。
環境変数 `Path` に追加する目的はなんですか？

2020-11-10 03:44 UTC, yuki-nakano commented on README.md
> +システム環境変数に新規で変数名に**DxLib**、変数値に先ほどコピーしたファイルパスの追加をしてください。次にシステム環境変数内からPathを探し編集から新規で<b>%DxLib%</b>の追加をお願いします。
環境変数を知らなかったので、調べていく中でシステム環境変数を使う際に必要なものだと思い込み記載しました。

2020-11-11 01:08 UTC, taishi-matsumura commented on README.md
> +システム環境変数に新規で変数名に**DxLib**、変数値に先ほどコピーしたファイルパスの追加をしてください。次にシステム環境変数内からPathを探し編集から新規で<b>%DxLib%</b>の追加をお願いします。
了解です。
`Path` への追加が不要であれば、その部分をREADMEから削除しておいてください。

2020-11-12 09:10 UTC, yuki-nakano commented on README.md
> +システム環境変数に新規で変数名に**DxLib**、変数値に先ほどコピーしたファイルパスの追加をしてください。次にシステム環境変数内からPathを探し編集から新規で<b>%DxLib%</b>の追加をお願いします。
028bb6e504406bbb367a1a101233aa58cce9778d　試してみて不要だったので、REDEMEからPath部分を削除しました。

2020-11-14 09:19 UTC, taishi-matsumura commented on README.md
> +システム環境変数に新規で変数名に**DxLib**、変数値に先ほどコピーしたファイルパスの追加をしてください。次にシステム環境変数内からPathを探し編集から新規で<b>%DxLib%</b>の追加をお願いします。
以前 @Takuto-Miyoshi のPRにも[コメント](https://github.com/human-osaka-game-2020/TrapAction_Miyoshi/pull/10#discussion_r507020672)したのですが、Path変数にパスを追加するのは、「追加した場所にあるexeをコマンドプロンプトからファイル名だけで実行したいとき 」が大半です。
例えばSourceTreeのターミナルから「git pull」のように打つだけでgitの実行ファイルのフルパスを打たなくても使用できるのは、Path変数に登録されているディレクトリにgitコマンドの実行ファイルが存在しているからです。

今回はそれには該当しないはずですのでPath変数への追加は不要ですね。

2020-11-14 09:21 UTC, taishi-matsumura requested changes
問題無さそうなので、コミットを整理してください。
fixupかsquashで一つに纏めてしまえば良いと思います。

2020-11-24 08:30 UTC, taishi-matsumura commented
他のクラスメイト同様、コミットメッセージの一行目にIssue IDを入れておいてください。
そうしておけばGitHubのコミット一覧画面からIssueにジャンプできるようになります。

今回の場合であれば `git rabase -i` をするまでもなく、`git commit --amend` で一行目を `REDEMEの更新 (#1)` 等に修正してforce pushすればOKですね。
SourceTreeのコミットボタンのプルダウンからamendできますよ。

2020-11-25 01:14 UTC, taishi-matsumura approved these changes

2020-11-25 01:14 UTC, merged